name: Calendar

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * MON-FRI"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  post_test:
    name: Runs the script and prints to the log
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ics
      - name: Run
        run: python3 ical_to_csv.py && cat cal_parsed.csv | python3 csv_to_calendar.py
