name: Calendar

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * MON"
  workflow_dispatch:

jobs:
  post_test:
    name: Runs the script and prints to the log
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ics requests
      - name: Run
        run: |
          python3 ical_to_csv.py
          echo Parsed calendar:
          cat cal_parsed.csv | tee events.csv
          echo Rendered messages:
          python3 csv_to_calendar.py
  post:
    name: Runs the script and posts to webhook
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ics requests
      - name: Run
        run: |
          python3 ical_to_csv.py 
          cat cal_parsed.csv | python3 csv_to_calendar.py 
          cat virtual.json | curl -X POST -H "Content-Type: application/json" --data @- $WEBHOOK
          cat in_person.json | curl -X POST -H "Content-Type: application/json" --data @- $WEBHOOK
          cat future.json | curl -X POST -H "Content-Type: application/json" --data @- $WEBHOOK
        env:
          WEBHOOK: ${{ secrets.CALENDAR_WEBHOOK }}
